# Generated by Django 4.1.2 on 2023-01-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_rename_name_animal_namef_rename_name_family_namea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
