# Generated by Django 4.1.2 on 2023-01-11 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicule', to='rent.vehicule'),
        ),
    ]
