# Generated by Django 4.1.2 on 2023-01-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_alter_rental_return_date_alter_rental_vehicule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='client',
            new_name='customer',
        ),
    ]
