# Generated by Django 4.1.2 on 2023-01-15 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_rename_client_rental_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='vehicule_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Size', to='rent.vehiculesize'),
        ),
    ]
