# Generated by Django 4.1.5 on 2023-01-09 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='phonne',
            new_name='phone',
        ),
    ]
