# Generated by Django 4.1.5 on 2023-01-09 11:23

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phonne', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('adresse', models.CharField(max_length=50)),
            ],
        ),
    ]
